# Generated by Django 3.0.5 on 2020-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID User')),
                ('name', models.TextField(verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
    ]
